SUMMARY = "Flutter Examples Package"
DESCRIPTION = "Flutter Plugin Examples Packagegroup"

inherit packagegroup

RDEPENDS:${PN} = "\
    flutter-plugin-example-battery-plus \
    flutter-plugin-example-connectivity-plus \
    flutter-plugin-example-device-info-plus \
    flutter-plugin-example-geolocator \
    flutter-plugin-example-google-maps \
    flutter-plugin-example-google-sign-in \
    flutter-plugin-example-gpiod \
    flutter-plugin-example-in-app-purchase \
    flutter-plugin-example-libserialport \
    flutter-plugin-example-linux-serial \
    flutter-plugin-example-linux-spidev \
    flutter-plugin-example-network-info-plus \
    flutter-plugin-example-package-info-plus \
    flutter-plugin-example-path-provider \
    flutter-plugin-example-shared-preferences \
    flutter-plugin-example-url-launcher \
    flutter-plugin-example-video-player \
    "
